spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/equipment_rds?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: zhangcaijian
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
